### ISSUE TITLE
javascript won't render on GitHub pages

### ISSUE THREAD

**Issue by louisgag** [louisgag/mbdyn-gsoc-projects#1]
Hi,
When I render this website forked from coala using the local python server, everything loads fine. However, when I visit the GitHub rendered page ( https://louisgag.github.io/mbdyn-gsoc-projects ) the javascript does not show. Did I miss something really basic about GitHub pages?

@sils following your suggestion
@hemangsk I was told you may know what hint to give me

Thanks,
-Louis

**Comment by hemangsk** [comment]
Hey Louis,
The issue due to which partials were unable to load was that the paths to partials inside app.js was
```
/partials/tabs/projects.html
```
And so angular searched for partials from the root of the url, (because of /projects)
Root of the url : http://louisgag.github.io, so the requested file by angular was http://louisgag.github.io/partials/tabs/projects.

https://github.com/louisgag/mbdyn-gsoc-projects/pull/2 will convert these urls to
```
partials/tabs/projects.html
```
So that these partials are searched in this repository, https://louisgag.github.io/mbdyn-gsoc-projects/partials/tabs/projects.html
